services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./iso-test-files:/app/iso-test-files
    environment:
      - DATABASE_URL=sqlite:////app/data/reports/iso_analysis.db
    restart: unless-stopped
    networks:
      - monitoring

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
     - "9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
    - "3001:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
